import DashboardHeader from "@/components/pages/dashboardComponents/DashboardHeader";
import { Metadata } from "next";
import { ReactNode } from "react";


export const metadata: Metadata = {
    title: "Dashboard | Products",
    description: "Generated by Next.js 14",
};

const dashboardLayout = ({ children }: {
    children: ReactNode;
}) => {
    return (
        <section className="max-w-screen-2xl mx-auto">
            <DashboardHeader />
            <main className="p-5 sm:p-10">
                {children}
            </main>
        </section>
    )
}

export default dashboardLayout;